"""empty message

Revision ID: 21d50d723d32
Revises: 4a55cf889c89
Create Date: 2020-12-13 18:34:51.336471

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21d50d723d32'
down_revision = '4a55cf889c89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'classes', 'curriculum', ['curriculum_id'], ['id'])
    op.create_foreign_key(None, 'classes', 'topic', ['topic_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'classes', type_='foreignkey')
    op.drop_constraint(None, 'classes', type_='foreignkey')
    # ### end Alembic commands ###
