"""empty message

Revision ID: 223fb5c5044a
Revises: b5fdf33a6c14
Create Date: 2020-12-13 17:46:09.197974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '223fb5c5044a'
down_revision = 'b5fdf33a6c14'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohort', sa.Column('name', sa.String(length=50), nullable=True))
    op.create_foreign_key(None, 'cohort', 'instructor', ['instructor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cohort', type_='foreignkey')
    op.drop_column('cohort', 'name')
    # ### end Alembic commands ###
