"""empty message

Revision ID: 268f523eae5e
Revises: 223fb5c5044a
Create Date: 2020-12-13 17:55:00.638507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '268f523eae5e'
down_revision = '223fb5c5044a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cohort', 'instructor', ['instructor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cohort', type_='foreignkey')
    # ### end Alembic commands ###
