"""empty message

Revision ID: 32cf09dbadb9
Revises: b8c8b3994353
Create Date: 2020-12-13 16:50:13.856539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32cf09dbadb9'
down_revision = 'b8c8b3994353'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('cohort_id', sa.Integer(), nullable=True, foreign_key='cohort.id'))
    op.drop_column('student', 'cohort')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('cohort', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('student', 'cohort_id')
    # ### end Alembic commands ###
