"""empty message

Revision ID: 36c1a7d4605f
Revises: de2b4a1a71b7
Create Date: 2020-12-12 17:50:31.625930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36c1a7d4605f'
down_revision = 'de2b4a1a71b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohort', 'name')
    op.add_column('event', sa.Column('time_to_pass', sa.Integer(), nullable=True))
    op.drop_column('event', 'time')
    op.add_column('topic', sa.Column('time_to_cover', sa.Integer(), nullable=True))
    op.drop_column('topic', 'time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topic', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('topic', 'time_to_cover')
    op.add_column('event', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('event', 'time_to_pass')
    op.add_column('cohort', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
