"""empty message

Revision ID: 4a55cf889c89
Revises: 6c716e5f34b7
Create Date: 2020-12-13 18:02:45.352231

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a55cf889c89'
down_revision = '6c716e5f34b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohort', sa.Column('name', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohort', 'name')
    # ### end Alembic commands ###
