"""empty message

Revision ID: 6c716e5f34b7
Revises: ace04a97ff7d
Create Date: 2020-12-13 18:01:26.282131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c716e5f34b7'
down_revision = 'ace04a97ff7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cohort', 'curriculum', ['curriculum'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cohort', type_='foreignkey')
    # ### end Alembic commands ###
