"""empty message

Revision ID: ace04a97ff7d
Revises: 268f523eae5e
Create Date: 2020-12-13 18:00:53.080568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ace04a97ff7d'
down_revision = '268f523eae5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'cohort', 'instructor', ['instructor'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'cohort', type_='foreignkey')
    # ### end Alembic commands ###
