"""empty message

Revision ID: b5fdf33a6c14
Revises: 32cf09dbadb9
Create Date: 2020-12-13 16:52:29.847675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5fdf33a6c14'
down_revision = '32cf09dbadb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'student', 'cohort', ['cohort_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'student', type_='foreignkey')
    # ### end Alembic commands ###
