"""empty message

Revision ID: b8c8b3994353
Revises: 36c1a7d4605f
Create Date: 2020-12-12 19:33:54.010166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8c8b3994353'
down_revision = '36c1a7d4605f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cohort', 'student_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cohort', sa.Column('student_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
