"""empty message

Revision ID: de2b4a1a71b7
Revises: 180ad8812f22
Create Date: 2020-12-12 16:17:34.564573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de2b4a1a71b7'
down_revision = '180ad8812f22'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.Column('curriculum_id', sa.Integer(), nullable=True)
    )
    op.add_column('curriculum', sa.Column('time_to_complete', sa.Integer(), nullable=True))
    op.drop_column('curriculum', 'topic_id')
    op.drop_column('curriculum', 'time')
    op.add_column('student', sa.Column('cohort', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('student', 'cohort')
    op.add_column('curriculum', sa.Column('time', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('curriculum', sa.Column('topic_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('curriculum', 'time_to_complete')
    op.drop_table('classes')
    # ### end Alembic commands ###
